FACEBOOK_APP_ID = ENV["FACEBOOK_APP_ID"]
FACEBOOK_APP_SECRET = ENV["FACEBOOK_APP_SECRET"]

TWITTER_CONSUMER_KEY = ENV["TWITTER_CONSUMER_KEY"]
TWITTER_CONSUMER_SECRET = ENV["TWITTER_CONSUMER_SECRET"]

FOURSQUARE_CLIENT_ID = ENV["FOURSQUARE_CLIENT_ID"]
FOURSQUARE_CLIENT_SECRET = ENV["FOURSQUARE_CLIENT_SECRET"]

API_BASE_URL = ENV["API_BASE_URL"]
API_KEY = ENV["API_KEY"]

COOKIE_SECRET = ENV['COOKIE_SECRET']
